http:
  routers:
    grafana:
      rule: Host(`grafana.localhost`)
      entryPoints: [websecure]
      tls: {}
      service: grafana
  services:
    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000
