http:
  routers:
    prometheus:
      rule: Host(`prometheus.localhost`)
      entryPoints: [websecure]
      tls: {}
      service: prometheus
  services:
    prometheus:
      loadBalancer:
        servers:
          - url: http://prometheus:9090
